(() => {
  const cube = new window.CubeState();
  const faces = ["U","L","F","R","B","D"];
  const order = ["U","R","F","D","L","B"];
  const moveTokens = ["R","R'","L","L'","U","U'","D","D'","F","F'","B","B'"];
  const colorHex = {U:"#f4f6f8",D:"#ffd43b",F:"#2ecc71",B:"#3498db",R:"#e74c3c",L:"#ff8c32"};
  const hexFace = Object.fromEntries(Object.entries(colorHex).map(([k,v])=>[v.toLowerCase(),k]));
  const algorithmDefs = [
    ["Sexy Move","R U R' U'"],["Middle right","U R U' R' U' F' U F"],["Middle left","U' L' U L U F U' F'"],["Yellow cross","F R U R' U' F'"],["Sune","R U R' U R U2 R'"],["T-permutation","R U R' U' R' F R2 U' R' U' R U R' F'"]
  ];

  const i18n = {
    "pt-BR":{projectLabel:"Treinador interativo · Cubo 3x3",mainTitle:"Aprenda, monte e resolva seu cubo",lead:"Use o cubo 3D, reproduza seu cubo físico ou acompanhe a solução movimento por movimento.",cube3d:"Cubo 3D",openView:"Vista aberta",scramble:"Embaralhar",reset:"Reiniciar",autoSolve:"Resolver automaticamente",teachMe:"Me ensine a resolver",myCube:"Colocar meu cubo",cubeHint:"Arraste para girar a visualização. Use os botões ao redor para girar as faces.",physicalCube:"Seu cubo físico",paintCube:"Monte abaixo exatamente como ele está",paintHelp:"Escolha uma cor e toque nos quadrados da vista aberta. Os centros ficam fixos.",resetColors:"Limpar",analyzeCube:"Analisar meu cubo",solutionGuide:"Guia de solução",solutionReady:"Solução pronta",nextMove:"Próximo movimento",lastSequence:"Última sequência",quickMoves:"Movimentos rápidos",faceTurns:"Giros das faces",runSequence:"Executar sequência",run:"Executar",acceptedMoves:"Aceitos: R L U D F B com ' ou 2.",cubeStatusLabel:"Estado",solved:"Resolvido",inProgress:"Em andamento",learnPractice:"Aprender e praticar",rightFace:"Face direita",leftFace:"Face esquerda",upperFace:"Face superior",downFace:"Face inferior",frontFace:"Face frontal",backFace:"Face traseira",randomPractice:"Prática aleatória",learned:n=>`${n}/6 algoritmos aprendidos`,invalidEntry:"Confira as cores: precisam existir exatamente 9 peças de cada cor.",invalidCube:"Esse estado não representa um cubo 3x3 solucionável. Confira as peças informadas.",alreadySolved:"O cubo já está resolvido.",preparing:"Preparando o resolvedor...",moveHelp:m=>`Faça o movimento ${m} no cubo. O sentido é definido olhando diretamente para essa face.`,done:"Cubo resolvido!"},
    en:{projectLabel:"Interactive trainer · 3x3 cube",mainTitle:"Learn, enter and solve your cube",lead:"Use the 3D cube, reproduce your physical cube, or follow the solution move by move.",cube3d:"3D cube",openView:"Open view",scramble:"Scramble",reset:"Reset",autoSolve:"Solve automatically",teachMe:"Teach me how to solve",myCube:"Enter my cube",cubeHint:"Drag to rotate the view. Use the buttons around the cube to turn its faces.",physicalCube:"Your physical cube",paintCube:"Match the view below to your real cube",paintHelp:"Choose a color and click the stickers. Centers stay fixed.",resetColors:"Clear",analyzeCube:"Analyze my cube",solutionGuide:"Solution guide",solutionReady:"Solution ready",nextMove:"Next move",lastSequence:"Last sequence",quickMoves:"Quick moves",faceTurns:"Face turns",runSequence:"Run sequence",run:"Run",acceptedMoves:"Accepted: R L U D F B with optional ' or 2.",cubeStatusLabel:"Status",solved:"Solved",inProgress:"In progress",learnPractice:"Learn and practice",rightFace:"Right face",leftFace:"Left face",upperFace:"Upper face",downFace:"Down face",frontFace:"Front face",backFace:"Back face",randomPractice:"Random practice",learned:n=>`${n}/6 algorithms learned`,invalidEntry:"Check the colors: there must be exactly 9 stickers of each color.",invalidCube:"This state is not a solvable 3x3 cube. Check the stickers you entered.",alreadySolved:"The cube is already solved.",preparing:"Preparing solver...",moveHelp:m=>`Perform ${m}. Direction is defined while looking directly at that face.`,done:"Cube solved!"},
    es:{projectLabel:"Entrenador interactivo · Cubo 3x3",mainTitle:"Aprende, configura y resuelve tu cubo",lead:"Usa el cubo 3D, reproduce tu cubo físico o sigue la solución movimiento a movimiento.",cube3d:"Cubo 3D",openView:"Vista abierta",scramble:"Mezclar",reset:"Reiniciar",autoSolve:"Resolver automáticamente",teachMe:"Enséñame a resolver",myCube:"Colocar mi cubo",cubeHint:"Arrastra para girar la vista. Usa los botones alrededor del cubo para mover las caras.",physicalCube:"Tu cubo físico",paintCube:"Configura la vista igual a tu cubo real",paintHelp:"Elige un color y toca las piezas. Los centros quedan fijos.",resetColors:"Limpiar",analyzeCube:"Analizar mi cubo",solutionGuide:"Guía de solución",solutionReady:"Solución lista",nextMove:"Siguiente movimiento",lastSequence:"Última secuencia",quickMoves:"Movimientos rápidos",faceTurns:"Giros de caras",runSequence:"Ejecutar secuencia",run:"Ejecutar",acceptedMoves:"Aceptados: R L U D F B con ' o 2 opcional.",cubeStatusLabel:"Estado",solved:"Resuelto",inProgress:"En progreso",learnPractice:"Aprender y practicar",rightFace:"Cara derecha",leftFace:"Cara izquierda",upperFace:"Cara superior",downFace:"Cara inferior",frontFace:"Cara frontal",backFace:"Cara trasera",randomPractice:"Práctica aleatoria",learned:n=>`${n}/6 algoritmos aprendidos`,invalidEntry:"Debe haber exactamente 9 piezas de cada color.",invalidCube:"Este estado no corresponde a un cubo 3x3 resoluble. Revisa las piezas.",alreadySolved:"El cubo ya está resuelto.",preparing:"Preparando el solucionador...",moveHelp:m=>`Haz el movimiento ${m}. El sentido se define mirando directamente esa cara.`,done:"¡Cubo resuelto!"},
    ja:{projectLabel:"インタラクティブ練習 · 3x3キューブ",mainTitle:"キューブを学び、入力し、解いてみよう",lead:"3Dキューブを操作し、実物の状態を入力して、一手ずつ解法を確認できます。",cube3d:"3Dキューブ",openView:"展開図",scramble:"スクランブル",reset:"リセット",autoSolve:"自動で解く",teachMe:"解き方を教える",myCube:"自分のキューブを入力",cubeHint:"ドラッグで視点を回転。周囲のボタンで各面を回します。",physicalCube:"実物のキューブ",paintCube:"実物と同じ状態に設定してください",paintHelp:"色を選び、展開図のステッカーをタップします。センターは固定です。",resetColors:"クリア",analyzeCube:"キューブを解析",solutionGuide:"解法ガイド",solutionReady:"解法準備完了",nextMove:"次の手",lastSequence:"直前の手順",quickMoves:"クイック操作",faceTurns:"面の回転",runSequence:"手順を実行",run:"実行",acceptedMoves:"使用可能: R L U D F B、' または 2。",cubeStatusLabel:"状態",solved:"完成",inProgress:"進行中",learnPractice:"学習と練習",rightFace:"右面",leftFace:"左面",upperFace:"上面",downFace:"下面",frontFace:"前面",backFace:"背面",randomPractice:"ランダム練習",learned:n=>`${n}/6 習得`,invalidEntry:"各色が正確に9枚あることを確認してください。",invalidCube:"この状態は解ける3x3キューブではありません。入力を確認してください。",alreadySolved:"すでに完成しています。",preparing:"ソルバーを準備中...",moveHelp:m=>`${m} を回してください。回転方向はその面を正面から見て判断します。`,done:"完成しました！"}
  };

  let lang = localStorage.getItem("ryCubeTrainer.lang") || "pt-BR";
  let busy=false, rotX=-24,rotY=36,dragging=false,lastX=0,lastY=0, entryMode=false, selectedColor="F";
  let solution=[], solutionIndex=0, autoplay=false, autoplayTimer=null, solverReady=false;
  const history=[]; const learned=loadLearned(); let currentPractice=null;
  const entryFaces = {};
  resetEntry();

  const $=id=>document.getElementById(id);
  const statusEl=$("cube-status"), compactStatus=$("compact-status"), learnedCountEl=$("learned-count"), historyEl=$("history-output"), inputEl=$("algorithm-input"), inputError=$("input-error"), entryError=$("entry-error"), moveButtonsEl=$("move-buttons"), algorithmListEl=$("algorithm-list"), view3d=$("cube-view-3d"), viewFlat=$("cube-view-flat"), cube3d=$("cube-3d"), cubeStage=$("cube-stage");

  init();

  function init(){
    $("language-select").value=lang; applyLanguage(); buildMoveButtons(); buildAlgorithms(); setupDrag(); bindEvents(); renderCube(); updateLearned(); setView("3d");
  }

  function t(k,...args){const v=(i18n[lang]||i18n["pt-BR"])[k];return typeof v==="function"?v(...args):(v||k)}
  function applyLanguage(){document.documentElement.lang=lang;document.querySelectorAll("[data-i18n]").forEach(el=>{el.textContent=t(el.dataset.i18n)});updateStatus();updateLearned();updateSolutionUI()}

  function bindEvents(){
    $("language-select").addEventListener("change",e=>{lang=e.target.value;localStorage.setItem("ryCubeTrainer.lang",lang);applyLanguage();buildAlgorithms()});
    $("view-3d-btn").addEventListener("click",()=>setView("3d")); $("view-flat-btn").addEventListener("click",()=>setView("flat"));
    $("recenter-btn").addEventListener("click",recenter);
    $("reset-btn").addEventListener("click",()=>{stopAutoplay();cube.reset();history.length=0;historyEl.textContent="—";solution=[];solutionIndex=0;entryMode=false;$("my-cube-panel").hidden=true;$("solution-panel").hidden=true;recenter();renderCube()});
    $("scramble-btn").addEventListener("click",async()=>{stopAutoplay();cube.reset();history.length=0;solution=[];$("solution-panel").hidden=true;const s=createScramble(20);inputEl.value=s.join(" ");await playTokens(s)});
    document.querySelectorAll("[data-direct-move]").forEach(b=>b.addEventListener("click",()=>playTokens([b.dataset.directMove])));
    $("algorithm-form").addEventListener("submit",async e=>{e.preventDefault();inputError.textContent="";try{const tokens=window.CubeState.parseSequence(inputEl.value);if(tokens.length)await playTokens(tokens)}catch(err){inputError.textContent=err.message}});
    $("auto-solve-btn").addEventListener("click",async()=>{const s=await solveCurrent();if(s.length){setSolution(s);await playTokens(s);solutionIndex=s.length;updateSolutionUI()}});
    $("teach-btn").addEventListener("click",async()=>{const s=await solveCurrent();if(s.length)setSolution(s)});
    $("my-cube-btn").addEventListener("click",openEntry); $("close-my-cube-btn").addEventListener("click",closeEntry); $("clear-entry-btn").addEventListener("click",()=>{resetEntry();renderCube()}); $("analyze-cube-btn").addEventListener("click",analyzeEntry);
    $("prev-step-btn").addEventListener("click",previousStep); $("play-step-btn").addEventListener("click",doNextStep); $("next-step-btn").addEventListener("click",doNextStep); $("autoplay-btn").addEventListener("click",toggleAutoplay);
    document.addEventListener("keydown",e=>{if(busy||e.ctrlKey||e.metaKey||e.altKey||e.target instanceof HTMLInputElement)return;const f=e.key.toUpperCase();if(faces.includes(f)){e.preventDefault();playTokens([f+(e.shiftKey?"'":"")])}});
    $("practice-btn").addEventListener("click",()=>{currentPractice=algorithmDefs[Math.floor(Math.random()*algorithmDefs.length)];$("practice-box").hidden=false;$("practice-name").textContent=currentPractice[0];$("practice-sequence").textContent=currentPractice[1];$("practice-sequence").classList.add("blurred")});
    $("reveal-btn").addEventListener("click",()=>$("practice-sequence").classList.toggle("blurred")); $("play-practice-btn").addEventListener("click",()=>currentPractice&&playTokens(window.CubeState.parseSequence(currentPractice[1])));
  }

  function recenter(){rotX=-24;rotY=36;updateRotation()}
  function setupDrag(){updateRotation();cubeStage.addEventListener("pointerdown",e=>{dragging=true;lastX=e.clientX;lastY=e.clientY;cubeStage.setPointerCapture(e.pointerId)});cubeStage.addEventListener("pointermove",e=>{if(!dragging)return;rotY+=(e.clientX-lastX)*.45;rotX-=(e.clientY-lastY)*.45;rotX=Math.max(-85,Math.min(85,rotX));lastX=e.clientX;lastY=e.clientY;updateRotation()});["pointerup","pointercancel"].forEach(n=>cubeStage.addEventListener(n,()=>dragging=false))}
  function updateRotation(){cube3d.style.transform=`rotateX(${rotX}deg) rotateY(${rotY}deg)`}
  function setView(mode){const d=mode==="3d";view3d.hidden=!d;view3d.style.display=d?"grid":"none";viewFlat.hidden=d;$("view-3d-btn").classList.toggle("is-active",d);$("view-flat-btn").classList.toggle("is-active",!d)}

  function renderFace(el,colors,face,isEntry=false){if(!el)return;if(el.children.length!==9){el.replaceChildren(...colors.map((_,i)=>{const s=document.createElement("div");s.className="sticker";s.dataset.index=i;s.dataset.face=face;return s}))}colors.forEach((c,i)=>{const s=el.children[i];s.style.backgroundColor=c;s.classList.toggle("editable",isEntry&&i!==4);s.onclick=isEntry&&i!==4?()=>{entryFaces[face][i]=selectedColor;renderCube()}:null})}
  function renderCube(){for(const f of faces){const actual=cube.getFace(f);renderFace($(`face3d-${f}`),actual,f,false);const flatColors=entryMode?entryFaces[f].map(x=>colorHex[x]):actual;renderFace($(`face-${f}`),flatColors,f,entryMode)}updateStatus()}
  function updateStatus(){const solved=cube.isSolved();const text=solved?t("solved"):t("inProgress");statusEl.textContent=text;compactStatus.textContent=text;compactStatus.style.color=solved?"var(--success)":"var(--accent2)"}

  async function playTokens(tokens){if(busy||!tokens.length)return;busy=true;try{for(const token of tokens){highlight(token[0]);await sleep(130);cube.applyMove(token);history.push(token);if(history.length>40)history.shift();historyEl.textContent=history.join(" ");renderCube();await sleep(90)}}finally{clearHighlight();busy=false}}
  function highlight(f){clearHighlight();document.querySelectorAll(`[data-face="${f}"]`).forEach(el=>el.classList.add("is-active"))}function clearHighlight(){document.querySelectorAll(".cube-face.is-active").forEach(el=>el.classList.remove("is-active"))}
  function inverseMove(m){if(m.endsWith("2"))return m;if(m.endsWith("'"))return m.slice(0,-1);return m+"'"}
  function inverseSequence(seq){return [...seq].reverse().map(inverseMove)}
  function createScramble(n){const fs=["R","L","U","D","F","B"],suf=["","'","2"],r=[];let p="";while(r.length<n){const f=fs[Math.floor(Math.random()*fs.length)];if(f===p)continue;r.push(f+suf[Math.floor(Math.random()*suf.length)]);p=f}return r}

  function faceletStringFromCube(){return order.flatMap(f=>cube.getFace(f).map(c=>hexFace[String(c).toLowerCase()])).join("")}
  async function ensureSolver(){if(solverReady)return;compactStatus.textContent=t("preparing");await sleep(30);if(!window.Cube||typeof window.Cube.initSolver!=="function")throw new Error("Solver unavailable");window.Cube.initSolver();solverReady=true;updateStatus()}
  async function solveString(str){await ensureSolver();const c=window.Cube.fromString(str);const raw=c.solve();return raw?raw.trim().split(/\s+/).filter(Boolean):[]}
  async function solveCurrent(){stopAutoplay();if(cube.isSolved()){compactStatus.textContent=t("alreadySolved");setTimeout(updateStatus,1200);return[]}try{return await solveString(faceletStringFromCube())}catch(e){inputError.textContent=t("invalidCube");return[]}}

  function setSolution(seq){solution=[...seq];solutionIndex=0;$("solution-panel").hidden=false;updateSolutionUI();$("solution-panel").scrollIntoView({behavior:"smooth",block:"center"})}
  function updateSolutionUI(){if(!$("solution-panel"))return;const total=solution.length;$("solution-progress").textContent=`${Math.min(solutionIndex+1,total)} / ${total}`;if(!total){$("current-solution-move").textContent="—";$("move-explanation").textContent="";return}if(solutionIndex>=total){$("current-solution-move").textContent="✓";$("move-explanation").textContent=t("done");$("solution-progress").textContent=`${total} / ${total}`}else{const m=solution[solutionIndex];$("current-solution-move").textContent=m;$("move-explanation").textContent=t("moveHelp",m)}const holder=$("solution-sequence");holder.replaceChildren(...solution.map((m,i)=>{const s=document.createElement("span");s.className="solution-token"+(i<solutionIndex?" done":"")+(i===solutionIndex?" current":"");s.textContent=m;return s}))}
  async function doNextStep(){if(busy||solutionIndex>=solution.length)return;await playTokens([solution[solutionIndex]]);solutionIndex++;updateSolutionUI();if(solutionIndex>=solution.length)stopAutoplay()}
  async function previousStep(){if(busy||solutionIndex<=0)return;stopAutoplay();solutionIndex--;await playTokens([inverseMove(solution[solutionIndex])]);updateSolutionUI()}
  function toggleAutoplay(){autoplay?stopAutoplay():startAutoplay()}
  function startAutoplay(){if(!solution.length||solutionIndex>=solution.length)return;autoplay=true;$("autoplay-btn").textContent="Ⅱ";runAutoplay()}
  function stopAutoplay(){autoplay=false;clearTimeout(autoplayTimer);autoplayTimer=null;if($("autoplay-btn"))$("autoplay-btn").textContent="▶"}
  async function runAutoplay(){if(!autoplay||solutionIndex>=solution.length){stopAutoplay();return}await doNextStep();if(autoplay){const ms=Number($("auto-delay-select").value)||2000;autoplayTimer=setTimeout(runAutoplay,ms)}}

  function resetEntry(){for(const f of faces)entryFaces[f]=Array(9).fill(f)}
  function openEntry(){stopAutoplay();entryMode=true;entryError.textContent="";$("my-cube-panel").hidden=false;setView("flat");buildPalette();renderCube();$("my-cube-panel").scrollIntoView({behavior:"smooth",block:"center"})}
  function closeEntry(){entryMode=false;$("my-cube-panel").hidden=true;renderCube()}
  function buildPalette(){const p=$("color-palette");p.replaceChildren(...order.map(f=>{const b=document.createElement("button");b.type="button";b.className="color-choice"+(f===selectedColor?" is-selected":"");b.style.background=colorHex[f];b.title=f;b.addEventListener("click",()=>{selectedColor=f;buildPalette()});return b}))}
  async function analyzeEntry(){entryError.textContent="";const counts={U:0,R:0,F:0,D:0,L:0,B:0};faces.forEach(f=>entryFaces[f].forEach(c=>counts[c]++));if(order.some(f=>counts[f]!==9)){entryError.textContent=t("invalidEntry");return}const str=order.flatMap(f=>entryFaces[f]).join("");try{const seq=await solveString(str);cube.reset();await playTokens(inverseSequence(seq));history.length=0;historyEl.textContent="—";entryMode=false;$("my-cube-panel").hidden=true;setView("3d");recenter();renderCube();if(seq.length)setSolution(seq);else{compactStatus.textContent=t("alreadySolved");setTimeout(updateStatus,1200)}}catch(e){entryError.textContent=t("invalidCube")}}

  function buildMoveButtons(){moveButtonsEl.replaceChildren(...moveTokens.map(m=>{const b=document.createElement("button");b.type="button";b.className="move-button";b.textContent=m;b.addEventListener("click",()=>playTokens([m]));return b}))}
  function buildAlgorithms(){algorithmListEl.replaceChildren(...algorithmDefs.map((a,idx)=>{const card=document.createElement("article");card.className="algorithm-card";const h=document.createElement("h3");h.textContent=a[0];const p=document.createElement("p");p.textContent=idx===0?"R U R' U'":"Pratique a sequência e acompanhe o cubo.";const code=document.createElement("code");code.className="algorithm-sequence";code.textContent=a[1];const actions=document.createElement("div");actions.className="algorithm-actions";const play=document.createElement("button");play.className="button secondary";play.type="button";play.textContent=t("run");play.addEventListener("click",()=>playTokens(window.CubeState.parseSequence(a[1])));const label=document.createElement("label");label.className="learn-toggle";const cb=document.createElement("input");cb.type="checkbox";cb.checked=learned.has(idx);cb.addEventListener("change",()=>{cb.checked?learned.add(idx):learned.delete(idx);saveLearned();updateLearned()});label.append(cb,document.createTextNode(" ✓"));actions.append(play,label);card.append(h,p,code,actions);return card}))}
  function loadLearned(){try{return new Set(JSON.parse(localStorage.getItem("ryCubeTrainer.learned")||"[]"))}catch{return new Set()}}function saveLearned(){localStorage.setItem("ryCubeTrainer.learned",JSON.stringify([...learned]))}function updateLearned(){if(learnedCountEl)learnedCountEl.textContent=t("learned",learned.size)}
  function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
})();