(() => {
  const cube = new window.CubeState();
  const faces = ["U", "L", "F", "R", "B", "D"];
  const moveTokens = ["R", "R'", "L", "L'", "U", "U'", "D", "D'", "F", "F'", "B", "B'"];

  const i18n = {
    "pt-BR": {
      language:"Idioma", projectLabel:"Projeto pessoal · Cubo 3x3", lead:"Aprenda a notação, execute algoritmos úteis e acompanhe o estado do cubo movimento por movimento.", cubeStatusLabel:"Estado do cubo", solved:"Resolvido", inProgress:"Em andamento", learnedCount:n=>`${n}/6 algoritmos aprendidos`, interactiveTrainer:"Treinador interativo", tryMoves:"Teste os movimentos", cube3d:"Cubo 3D", openView:"Vista aberta", scramble:"Embaralhar", reset:"Reiniciar", cubeHint:"Arraste o cubo para girar a visualização. Use os botões de movimento para girar as faces.", lastSequence:"Última sequência", faceTurns:"Giros das faces", quickMoves:"Movimentos rápidos", quickHelp:"O apóstrofo indica o movimento inverso. Você também pode usar o teclado: R, L, U, D, F ou B. Segure Shift para o movimento inverso.", runSequence:"Executar sequência", run:"Executar", acceptedMoves:"Movimentos aceitos: R L U D F B com ' ou 2 opcional.", typeMove:"Digite pelo menos um movimento.", startHere:"Comece aqui", notationTitle:"Notações que vale a pena memorizar", rightFace:"Face direita", leftFace:"Face esquerda", upperFace:"Face superior", downFace:"Face inferior", frontFace:"Face frontal", backFace:"Face traseira", inverseTurn:"Giro inverso", halfTurn:"Meia volta", clockwiseNote:"O sentido horário é sempre definido olhando diretamente para a face que está sendo girada.", buildingBlocks:"Blocos fundamentais", algorithmsTitle:"Algoritmos para praticar", randomPractice:"Prática aleatória", practice:"Prática", reveal:"Mostrar", hide:"Ocultar", playIt:"Executar", play:"Executar", learned:"Aprendido", beginnerRoadmap:"Roteiro para iniciantes", roadmapTitle:"Uma ordem prática para aprender", whiteCross:"Cruz branca", whiteCrossDesc:"Aprenda a alinhar cada aresta com o centro lateral correspondente, não apenas formar uma cruz branca.", firstCorners:"Cantos da primeira camada", firstCornersDesc:"Ganhe familiaridade com sequências curtas como R U R' U'.", middleLayer:"Camada do meio", middleLayerDesc:"Pratique inserir uma aresta à direita e à esquerda.", yellowCross:"Cruz amarela", yellowCrossDesc:"Reconheça os casos ponto, L e linha antes de executar o algoritmo.", orientYellow:"Orientar a face amarela", orientYellowDesc:"Sune é um padrão útil para reconhecer desde cedo.", lastPositioning:"Posicionamento da última camada", lastPositioningDesc:"Aprenda os casos de permutação gradualmente, em vez de tentar memorizar tudo de uma vez.", footer:"Criado por Takero Yanase como projeto pessoal para um portfólio técnico público.",
      algorithms:[
        ["Sexy Move","Uma sequência curta que aparece em muitos casos básicos e avançados. Vale a pena automatizá-la."],
        ["Camada do meio — inserir à direita","Usado no método iniciante quando uma aresta da camada superior deve entrar na camada do meio à direita."],
        ["Camada do meio — inserir à esquerda","Inserção espelhada para uma aresta que deve ir para a esquerda."],
        ["Cruz amarela","Sequência comum para orientar as arestas da última camada e formar a cruz amarela."],
        ["Sune","Um dos padrões mais reconhecíveis de orientação da última camada."],
        ["Permutação T","Uma permutação clássica da última camada, útil para treinar precisão."]
      ]
    },
    en: {
      language:"Language", projectLabel:"Personal project · 3x3 cube", lead:"Learn the notation, run useful algorithms and watch the cube state change move by move.", cubeStatusLabel:"Cube status", solved:"Solved", inProgress:"In progress", learnedCount:n=>`${n}/6 algorithms learned`, interactiveTrainer:"Interactive trainer", tryMoves:"Try the moves", cube3d:"3D cube", openView:"Open view", scramble:"Scramble", reset:"Reset", cubeHint:"Drag the cube to rotate the view. Use the move buttons to turn its faces.", lastSequence:"Last sequence", faceTurns:"Face turns", quickMoves:"Quick moves", quickHelp:"A prime mark means the inverse direction. Use the keyboard too: R, L, U, D, F or B. Hold Shift for the prime move.", runSequence:"Run a sequence", run:"Run", acceptedMoves:"Accepted moves: R L U D F B with optional ' or 2.", typeMove:"Type at least one move.", startHere:"Start here", notationTitle:"Notation that is worth memorizing", rightFace:"Right face", leftFace:"Left face", upperFace:"Upper face", downFace:"Down face", frontFace:"Front face", backFace:"Back face", inverseTurn:"Inverse turn", halfTurn:"Half turn", clockwiseNote:"Clockwise is always defined while you are looking directly at the face you are turning.", buildingBlocks:"Useful building blocks", algorithmsTitle:"Algorithms to practice", randomPractice:"Random practice", practice:"Practice", reveal:"Reveal", hide:"Hide", playIt:"Play it", play:"Play", learned:"Learned", beginnerRoadmap:"Beginner roadmap", roadmapTitle:"A sensible order to learn", whiteCross:"White cross", whiteCrossDesc:"Learn to match each edge with its side center instead of only making a white plus.", firstCorners:"First-layer corners", firstCornersDesc:"Get comfortable with short triggers such as R U R' U'.", middleLayer:"Middle layer", middleLayerDesc:"Practice inserting an edge to the right and to the left.", yellowCross:"Yellow cross", yellowCrossDesc:"Recognize the dot, L and line cases before running the algorithm.", orientYellow:"Orient the yellow face", orientYellowDesc:"Sune is a useful pattern to recognize early.", lastPositioning:"Last-layer positioning", lastPositioningDesc:"Learn permutation cases gradually instead of trying to memorize everything at once.", footer:"Built by Takero Yanase as a hobby project for a public technical portfolio.",
      algorithms:[["Sexy Move","A short trigger that appears in many beginner and advanced cases. It is worth making this one feel automatic."],["Middle layer — right insert","Used in the beginner method when a top-layer edge belongs in the middle layer on the right."],["Middle layer — left insert","The mirrored middle-layer insertion for an edge that needs to move to the left."],["Yellow cross","A common beginner sequence for orienting the last-layer edges and building the yellow cross."],["Sune","One of the most recognizable last-layer orientation patterns."],["T-permutation","A classic last-layer permutation, useful practice for accurate execution."]]
    },
    es: {
      language:"Idioma", projectLabel:"Proyecto personal · Cubo 3x3", lead:"Aprende la notación, ejecuta algoritmos útiles y observa cómo cambia el cubo movimiento a movimiento.", cubeStatusLabel:"Estado del cubo", solved:"Resuelto", inProgress:"En progreso", learnedCount:n=>`${n}/6 algoritmos aprendidos`, interactiveTrainer:"Entrenador interactivo", tryMoves:"Prueba los movimientos", cube3d:"Cubo 3D", openView:"Vista abierta", scramble:"Mezclar", reset:"Reiniciar", cubeHint:"Arrastra el cubo para girar la vista. Usa los botones para mover sus caras.", lastSequence:"Última secuencia", faceTurns:"Giros de caras", quickMoves:"Movimientos rápidos", quickHelp:"El apóstrofo indica el movimiento inverso. También puedes usar R, L, U, D, F o B en el teclado. Mantén Shift para el movimiento inverso.", runSequence:"Ejecutar secuencia", run:"Ejecutar", acceptedMoves:"Movimientos aceptados: R L U D F B con ' o 2 opcional.", typeMove:"Escribe al menos un movimiento.", startHere:"Empieza aquí", notationTitle:"Notación que vale la pena memorizar", rightFace:"Cara derecha", leftFace:"Cara izquierda", upperFace:"Cara superior", downFace:"Cara inferior", frontFace:"Cara frontal", backFace:"Cara trasera", inverseTurn:"Giro inverso", halfTurn:"Media vuelta", clockwiseNote:"El sentido horario se define mirando directamente la cara que se está girando.", buildingBlocks:"Bloques fundamentales", algorithmsTitle:"Algoritmos para practicar", randomPractice:"Práctica aleatoria", practice:"Práctica", reveal:"Mostrar", hide:"Ocultar", playIt:"Ejecutar", play:"Ejecutar", learned:"Aprendido", beginnerRoadmap:"Ruta para principiantes", roadmapTitle:"Un orden práctico para aprender", whiteCross:"Cruz blanca", whiteCrossDesc:"Aprende a alinear cada arista con su centro lateral, no solo a formar una cruz blanca.", firstCorners:"Esquinas de la primera capa", firstCornersDesc:"Practica secuencias cortas como R U R' U'.", middleLayer:"Capa intermedia", middleLayerDesc:"Practica insertar una arista a la derecha y a la izquierda.", yellowCross:"Cruz amarilla", yellowCrossDesc:"Reconoce los casos punto, L y línea antes de ejecutar el algoritmo.", orientYellow:"Orientar la cara amarilla", orientYellowDesc:"Sune es un patrón útil para reconocer desde el principio.", lastPositioning:"Posición de la última capa", lastPositioningDesc:"Aprende los casos de permutación gradualmente en lugar de memorizar todo a la vez.", footer:"Creado por Takero Yanase como proyecto personal para un portafolio técnico público.",
      algorithms:[["Sexy Move","Secuencia corta presente en muchos casos básicos y avanzados."],["Capa intermedia — insertar a la derecha","Se usa cuando una arista superior debe entrar en la capa intermedia por la derecha."],["Capa intermedia — insertar a la izquierda","Inserción reflejada para una arista que debe ir a la izquierda."],["Cruz amarilla","Secuencia común para orientar las aristas de la última capa."],["Sune","Uno de los patrones más reconocibles de orientación de la última capa."],["Permutación T","Permutación clásica de la última capa, útil para practicar precisión."]]
    },
    ja: {
      language:"言語", projectLabel:"個人プロジェクト · 3x3キューブ", lead:"記号を学び、便利なアルゴリズムを実行し、キューブの状態変化を一手ずつ確認できます。", cubeStatusLabel:"キューブの状態", solved:"完成", inProgress:"進行中", learnedCount:n=>`${n}/6 アルゴリズム習得`, interactiveTrainer:"インタラクティブ練習", tryMoves:"動かしてみる", cube3d:"3Dキューブ", openView:"展開図", scramble:"スクランブル", reset:"リセット", cubeHint:"キューブをドラッグして視点を回転できます。ボタンで各面を動かせます。", lastSequence:"直前の手順", faceTurns:"面の回転", quickMoves:"クイック操作", quickHelp:"' は逆回転を表します。キーボードの R, L, U, D, F, B も使用できます。Shift を押すと逆回転です。", runSequence:"手順を実行", run:"実行", acceptedMoves:"使用可能: R L U D F B。' または 2 を追加できます。", typeMove:"少なくとも1手入力してください。", startHere:"ここから開始", notationTitle:"覚えておきたい記号", rightFace:"右面", leftFace:"左面", upperFace:"上面", downFace:"下面", frontFace:"前面", backFace:"背面", inverseTurn:"逆回転", halfTurn:"180度回転", clockwiseNote:"時計回りは、回す面を正面から見た方向で定義されます。", buildingBlocks:"基本パターン", algorithmsTitle:"練習するアルゴリズム", randomPractice:"ランダム練習", practice:"練習", reveal:"表示", hide:"隠す", playIt:"実行", play:"実行", learned:"習得済み", beginnerRoadmap:"初心者ロードマップ", roadmapTitle:"おすすめの学習順序", whiteCross:"白十字", whiteCrossDesc:"白い十字だけでなく、各エッジを側面のセンターにも合わせます。", firstCorners:"1層目のコーナー", firstCornersDesc:"R U R' U' のような短い手順に慣れます。", middleLayer:"中段", middleLayerDesc:"エッジを右と左に入れる手順を練習します。", yellowCross:"黄十字", yellowCrossDesc:"点、L字、線のパターンを見分けてからアルゴリズムを実行します。", orientYellow:"黄色面を揃える", orientYellowDesc:"Suneは早めに覚えると便利なパターンです。", lastPositioning:"最終層の配置", lastPositioningDesc:"すべてを一度に暗記せず、順番にパターンを覚えます。", footer:"Takero Yanase が公開技術ポートフォリオ用の個人プロジェクトとして制作しました。",
      algorithms:[["セクシームーブ","初心者から上級者まで多くの場面で使われる短い基本手順です。"],["中段 — 右入れ","上段のエッジを中段の右側へ入れる手順です。"],["中段 — 左入れ","エッジを左側へ入れる鏡像手順です。"],["黄十字","最終層のエッジを向けて黄十字を作る基本手順です。"],["Sune","最終層の向きを揃える代表的なパターンです。"],["Tパーム","最終層の代表的な置換手順で、正確さの練習に向いています。"]]
    }
  };

  const algorithmDefs = [
    ["sexy-move","R U R' U'"], ["middle-right","U R U' R' U' F' U F"], ["middle-left","U' L' U L U F U' F'"], ["yellow-cross","F R U R' U' F'"], ["sune","R U R' U R U2 R'"], ["t-perm","R U R' U' R' F R2 U' R' U' R U R' F'"]
  ];

  const history=[]; let busy=false, currentPractice=null; const learned=loadLearned();
  const statusEl=document.getElementById("cube-status"), learnedCountEl=document.getElementById("learned-count"), historyEl=document.getElementById("history-output"), inputEl=document.getElementById("algorithm-input"), errorEl=document.getElementById("input-error"), moveButtonsEl=document.getElementById("move-buttons"), algorithmListEl=document.getElementById("algorithm-list"), practiceBoxEl=document.getElementById("practice-box"), practiceNameEl=document.getElementById("practice-name"), practiceSequenceEl=document.getElementById("practice-sequence"), languageSelect=document.getElementById("language-select");
  const view3d=document.getElementById("cube-view-3d"), viewFlat=document.getElementById("cube-view-flat"), view3dBtn=document.getElementById("view-3d-btn"), viewFlatBtn=document.getElementById("view-flat-btn"), cube3d=document.getElementById("cube-3d"), cubeStage=document.getElementById("cube-stage");
  let rotX=-24,rotY=36,dragging=false,lastX=0,lastY=0;
  let currentLang=localStorage.getItem("ryCubeTrainer.language") || "pt-BR";
  if(!i18n[currentLang]) currentLang="pt-BR";
  languageSelect.value=currentLang;

  buildMoveButtons(); buildAlgorithmCards(); setLanguage(currentLang); renderCube(); setView("3d"); setup3dDrag();
  languageSelect.addEventListener("change",()=>setLanguage(languageSelect.value));
  view3dBtn.addEventListener("click",()=>setView("3d")); viewFlatBtn.addEventListener("click",()=>setView("flat"));

  document.getElementById("algorithm-form").addEventListener("submit",async e=>{e.preventDefault();errorEl.textContent="";try{const tokens=window.CubeState.parseSequence(inputEl.value);if(!tokens.length){errorEl.textContent=t().typeMove;return}await playTokens(tokens)}catch(err){errorEl.textContent=err.message}});
  document.getElementById("reset-btn").addEventListener("click",()=>{if(busy)return;cube.reset();history.length=0;historyEl.textContent="—";errorEl.textContent="";renderCube()});
  document.getElementById("scramble-btn").addEventListener("click",async()=>{if(busy)return;cube.reset();history.length=0;renderCube();const s=createScramble(20);inputEl.value=s.join(" ");await playTokens(s)});
  document.getElementById("practice-btn").addEventListener("click",()=>{const idx=Math.floor(Math.random()*algorithmDefs.length);currentPractice={idx,sequence:algorithmDefs[idx][1]};practiceBoxEl.hidden=false;practiceNameEl.textContent=t().algorithms[idx][0];practiceSequenceEl.textContent=currentPractice.sequence;practiceSequenceEl.classList.add("blurred");document.getElementById("reveal-btn").textContent=t().reveal});
  document.getElementById("reveal-btn").addEventListener("click",()=>{if(!currentPractice)return;const hidden=practiceSequenceEl.classList.toggle("blurred");document.getElementById("reveal-btn").textContent=hidden?t().reveal:t().hide});
  document.getElementById("play-practice-btn").addEventListener("click",async()=>{if(!currentPractice||busy)return;practiceSequenceEl.classList.remove("blurred");await playTokens(window.CubeState.parseSequence(currentPractice.sequence))});
  document.addEventListener("keydown",async e=>{if(busy||e.ctrlKey||e.metaKey||e.altKey||e.target instanceof HTMLInputElement||e.target instanceof HTMLSelectElement)return;const face=e.key.toUpperCase();if(!faces.includes(face))return;e.preventDefault();await playTokens([`${face}${e.shiftKey?"'":""}`])});

  function t(){return i18n[currentLang]}
  function setLanguage(lang){currentLang=i18n[lang]?lang:"pt-BR";languageSelect.value=currentLang;document.documentElement.lang=currentLang;localStorage.setItem("ryCubeTrainer.language",currentLang);document.querySelectorAll("[data-i18n]").forEach(el=>{const key=el.dataset.i18n;if(typeof t()[key]==="string")el.textContent=t()[key]});refreshAlgorithmCards();if(currentPractice)practiceNameEl.textContent=t().algorithms[currentPractice.idx][0];renderCube();updateLearnedCount()}
  function setView(mode){const is3d=mode==="3d";view3d.hidden=!is3d;viewFlat.hidden=is3d;view3d.style.display=is3d?"grid":"none";view3dBtn.classList.toggle("is-selected",is3d);viewFlatBtn.classList.toggle("is-selected",!is3d);localStorage.setItem("ryCubeTrainer.view",mode)}
  function setup3dDrag(){const update=()=>cube3d.style.transform=`rotateX(${rotX}deg) rotateY(${rotY}deg)`;update();cubeStage.addEventListener("pointerdown",e=>{dragging=true;lastX=e.clientX;lastY=e.clientY;cubeStage.setPointerCapture(e.pointerId)});cubeStage.addEventListener("pointermove",e=>{if(!dragging)return;rotY+=(e.clientX-lastX)*.45;rotX-=(e.clientY-lastY)*.45;rotX=Math.max(-85,Math.min(85,rotX));lastX=e.clientX;lastY=e.clientY;update()});const stop=()=>dragging=false;cubeStage.addEventListener("pointerup",stop);cubeStage.addEventListener("pointercancel",stop)}
  function buildMoveButtons(){for(const move of moveTokens){const b=document.createElement("button");b.type="button";b.className="move-button";b.textContent=move;b.addEventListener("click",()=>playTokens([move]));moveButtonsEl.appendChild(b)}}
  function buildAlgorithmCards(){algorithmDefs.forEach((def,idx)=>{const card=document.createElement("article");card.className="algorithm-card";card.dataset.idx=idx;const title=document.createElement("h3");title.className="alg-title";const desc=document.createElement("p");desc.className="alg-desc";const seq=document.createElement("code");seq.className="algorithm-sequence";seq.textContent=def[1];const actions=document.createElement("div");actions.className="algorithm-actions";const play=document.createElement("button");play.type="button";play.className="button secondary alg-play";play.addEventListener("click",()=>{inputEl.value=def[1];playTokens(window.CubeState.parseSequence(def[1]))});const label=document.createElement("label");label.className="learn-toggle";const cb=document.createElement("input");cb.type="checkbox";cb.checked=learned.has(def[0]);cb.addEventListener("change",()=>{cb.checked?learned.add(def[0]):learned.delete(def[0]);saveLearned();updateLearnedCount()});const labelText=document.createElement("span");labelText.className="learn-text";label.append(cb,labelText);actions.append(play,label);card.append(title,desc,seq,actions);algorithmListEl.appendChild(card)})}
  function refreshAlgorithmCards(){document.querySelectorAll(".algorithm-card").forEach(card=>{const idx=Number(card.dataset.idx);card.querySelector(".alg-title").textContent=t().algorithms[idx][0];card.querySelector(".alg-desc").textContent=t().algorithms[idx][1];card.querySelector(".alg-play").textContent=t().play;card.querySelector(".learn-text").textContent=t().learned})}
  async function playTokens(tokens){if(busy||!tokens.length)return;setBusy(true);try{for(const token of tokens){highlightFace(token[0]);await sleep(150);cube.applyMove(token);history.push(token);if(history.length>30)history.shift();historyEl.textContent=history.join(" ");renderCube();await sleep(90)}}finally{clearHighlights();setBusy(false)}}
  function renderFace(element,colors){if(!element)return;if(element.children.length!==9){element.replaceChildren(...colors.map(()=>{const s=document.createElement("div");s.className="sticker";return s}))}colors.forEach((c,i)=>element.children[i].style.backgroundColor=c)}
  function renderCube(){for(const face of faces){const colors=cube.getFace(face);renderFace(document.getElementById(`face-${face}`),colors);renderFace(document.getElementById(`face3d-${face}`),colors)}statusEl.textContent=cube.isSolved()?t().solved:t().inProgress}
  function highlightFace(face){clearHighlights();document.querySelectorAll(`[data-face="${face}"]`).forEach(el=>el.classList.add("is-active"))}
  function clearHighlights(){document.querySelectorAll(".cube-face.is-active").forEach(el=>el.classList.remove("is-active"))}
  function setBusy(v){busy=v;document.querySelectorAll("button").forEach(b=>b.disabled=v)}
  function createScramble(length){const fs=["R","L","U","D","F","B"],ss=["","'","2"],r=[];let prev="";while(r.length<length){const f=fs[Math.floor(Math.random()*fs.length)];if(f===prev)continue;r.push(f+ss[Math.floor(Math.random()*ss.length)]);prev=f}return r}
  function loadLearned(){try{const saved=JSON.parse(localStorage.getItem("ryCubeTrainer.learned")||"[]");return new Set(Array.isArray(saved)?saved:[])}catch{return new Set()}}
  function saveLearned(){localStorage.setItem("ryCubeTrainer.learned",JSON.stringify([...learned]))}
  function updateLearnedCount(){learnedCountEl.textContent=t().learnedCount(learned.size)}
  function sleep(ms){return new Promise(resolve=>setTimeout(resolve,ms))}
})();
